site_name: proto
nav:
  - Overview: "index.md"
  - API:
      - API: "proto/api.md"
      - BlockService: "proto/block.md"
      - NodeAdminService: "proto/node_admin.md"
      - NodeUserService: "proto/node_user.md"
      - NodeWalletManager: "proto/node_wallet_manager.md"
