name: Publish Node.js Package

on:
  workflow_dispatch: {}
  push:
    paths:
      - "node/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - run: |
          cd typescript
          npm install
          npm run build
          npm run bump
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
